spring.profiles.active=dev

spring.flyway.enabled=${FLYWAY_ENABLED:false}

server.port=8081

spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB

logging.level.root=INFO